a = input("Type something: ")
print("What you type is a",type(a))
print("Just space? ", a.isspace())
print("Is a number? ", a.isnumeric())
print("Is a char? ", a.isalpha())
print("Is alphanumeric? ", a.isalnum())
print("Is just upper? ", a.isupper())
print("Is just lower? ", a.islower())
print("Is captalized? ", a.istitle())
